id     = "Counting"
name   = "ModelCounting"

[[option]]
  name       = "bitblastApproxMC"
  category   = "regular"
  long       = "blast-apxmc"
  short      = "b"
  type       = "bool"
  default    = "false"
  alternate  = false
  help       = "bitblast and count using ApproxMC"

[[option]]
  name       = "enumerateCount"
  category   = "regular"
  long       = "countenum"
  short      = "e"
  type       = "bool"
  default    = "false"
  alternate  = false
  help       = "count by enumeration"

[[option]]
  name       = "smtapproxMC"
  category   = "regular"
  long       = "smtapxmc"
  short      = "S"
  type       = "bool"
  default    = "false"
  alternate  = false
  help       = "approximate model count using SMTApproxMC"

[[option]]
  name       = "printHashedConstraints"
  category   = "regular"
  long       = "printhash"
  type       = "bool"
  default    = "false"
  alternate  = false
  help       = "Print Hashing constraints added (as .smt files)"

[[option]]
  name       = "countingverb"
  category   = "regular"
  long       = "cv"
  type       = "bool"
  default    = "false"
  help       = "verbosity while counting"

[[option]]
  name       = "projcount"
  category   = "regular"
  long       = "projcount"
  type       = "bool"
  default    = "false"
  alternate  = false
  help       = "Project the count on reachability variables"

[[option]]
  name       = "projprefix"
  category   = "regular"
  long       = "projprefix=PREFIX"
  type       = "std::string"
  default    = '""'
  help       = "prefix of projection variables"

[[option]]
  name       = "hashsm"
  category   = "regular"
  long       = "hashsm=MODE"
  type       = "HashingMode"
  default    = "BV"
  help       = "choose which hashing method to use BV, INT or FF"
  help_mode  = "choose which hashing method to use"
[[option.mode.BV]]
  name = "bv"
[[option.mode.FF]]
  name = "ff"
[[option.mode.INT]]
  name = "int"

[[option]]
  name       = "slicesize"
  category   = "regular"
  long       = "slicesize=N"
  type       = "uint64_t"
  default    = "0"
  help       = "slice size in SMTApproxMC"
